# Generated by Django 4.1.13 on 2024-08-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0004_tutor_alter_ficha_programa_ficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='usuario_ingreso',
            field=models.ForeignKey(db_column='usuario_ingreso', default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrofacial',
            name='usuario_registro_facial',
            field=models.ForeignKey(db_column='usuario_registro_facial', default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(db_column='ficha_usuario', default=1, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha'),
        ),
    ]
