# Generated by Django 4.1.13 on 2024-08-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0005_alter_ingreso_usuario_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ficha_usuario',
            field=models.ForeignKey(db_column='ficha_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_senauthenticator.ficha'),
        ),
    ]
