# Generated by Django 4.1.13 on 2024-08-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_senauthenticator', '0006_alter_usuario_ficha_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficina', models.CharField(db_column='nombre_oficina', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_usuario',
            field=models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Administrador', 'Administrador'), ('Usuario', 'Usuario'), ('Guardia de seguridad', 'Guardia de seguridad')], db_column='rol_usuario', default='Aprendiz', max_length=20),
        ),
    ]
